### ISSUE TITLE
Statement for an anonymous class object gives an NPE

### ISSUE THREAD

**Issue by dakusui** [valid8j/valid8j#20]
If a `Key` is an object of an anonymous class, an NPE will be thrown.

```java
    Key key = ExecutionProfile.create().totpKey();
    
    assertAll(value(key).toBe().instanceOf(SecretKey.class),
              value(key).function(Key::getAlgorithm).toBe().equalTo("MAC-SHA1"),
              value(key).function(Key::getFormat).toBe().nullValue(),
              value(key).function(Key::getEncoded).toBe().instanceOf(byte[].class));
```

**Comment by dakusui** [comment]
```
java.lang.NullPointerException: Cannot invoke "java.lang.Package.getName()" because the return value of "java.lang.Class.getPackage()" is null

	at com.github.valid8j.pcond.internals.InternalUtils._formatObject(InternalUtils.java:81)
	at com.github.valid8j.pcond.internals.InternalUtils.formatObject(InternalUtils.java:38)
	at com.github.valid8j.pcond.internals.InternalUtils.formatObject(InternalUtils.java:34)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.github.valid8j.pcond.internals.InternalUtils._formatObject(InternalUtils.java:50)
	at com.github.valid8j.pcond.internals.InternalUtils.formatObject(InternalUtils.java:38)
	at com.github.valid8j.pcond.internals.InternalUtils.formatObject(InternalUtils.java:34)
	at com.github.valid8j.pcond.validator.MessageComposer$Default.composeMessageForAssertion(MessageComposer.java:74)
```
